version: "3.9"

services:
  thghosting-client:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: thghosting-client
    restart: always
    tty: true
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - PUID=1000
      - PGID=1000
